#640, 480

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

HALF_WIDTH = SCREEN_WIDTH//2
HALF_HEIGHT = SCREEN_HEIGHT//2

GREEN = 'G'
AMBER = 'A'
RED = 'R'
START = 'S'
FINISH = 'F'
REGEN = 'H'
TRAP = 'T'
OBSTACLE = 'O'
DISAPPEAR = 'D'

HIDE_TIMER = 3500

NORTH = (-4, 0)
SOUTH = (4, 0)
EAST = (0, 4)
WEST = (0, -4)

ANGLE_LOOKUP = {NORTH: 360, SOUTH: 180, EAST: 270, WEST: 90}

