levels = [['OOOOOOO',
           'OHGATAO',
           'OGRORFO',
           'OSRRAGO',
           'OGDGGTO',
           'OOOOOOO'],

          ['OOOOOOOOOOOOOOOOOOOOOOOOOOOO',
           'OHXXRXXXRXXXXXXRXXXXGGGAGAGO',
           'OBRXXXRXXXXRXXXXXRXXGGGGRDTO',
           'OGGOOOOOOOOOOOOOOOOOOGTHTGRO',
           'OTGARAOGDHARDTGGRGRHGTGAGRAO',
           'OGRAAHOATAGAGAGRARAGAGATARGO',
           'ORARRGOTAAAGTGHGDGTGGGGRGHAO',
           'ORRRARORGARGOOOOOOOOOOGRGAGO',
           'ORAAGROGRGGAO        OGARGRO',
           'ORRFRRORGAHGO        ODAGTGO',
           'OOOOOOOGTGRAOOOOOOOOOOGADGDO',
           'OGDGRGADGAGRGAGDAGGATAGRGHHO',
           'OSATGGHRTGAGTRDHGTAGRGATGRTO',
           'OGAGGRAGDGTHGGTGDGTGHGDAADHO',
           'OOOOOOOOOOOOOOOOOOOOOOOOOOOO'],

          ['OOOOOOOOOOOOOOOOOOOOOOOOOOOO',
           'OXXXXXXXRXXXXXXXXXAXXXTXXXXO',
           'OXXXXTXXXXXXXRXXXXXXXXXXXXXO',
           'OXXXXHXXXXGXXXXTXXXXXGXXXXTO',
           'OXXXXTXXAXXXXXXXXXXXXXXHXXXO',
           'OXXXXXXXXXXTXXXXXXAXXXXXXXXO',
           'OXXRXGXXXXXXXXXXXXXXXXTXRXXO',
           'OXXXXXXXXXXXXXXXRXXGXXXXXXXO',
           'OXXXXXTXXXXXXXXXXXXXXXXGXXXO',
           'OXRXXXXRXXXXGXXXXGXXXXRXXXXO',
           'OXXXXGXXXXXXXXSXXXXXXXTXXXXO',
           'OXXXXXXXXXGXXXXXXXAXXXXXXXXO',
           'OTXXXXRXXXXGXXXXGXXXXXXXXXXO',
           'OXXXRXXXXXXXXXXXXTXXXXAXXXRO',
           'OXHXXAXXXXXGXXXXXXXXXXXXXXTO',
           'OXXXAXXTXXXXXXXXHXXXXXRXXXXO',
           'OXXXXXXXXXRXXXXXTXXXXXXXXXXO',
           'OXXTXXXAXXXXAXXXRXXXXXFXXXXO',
           'OOOOOOOOOOOOOOOOOOOOOOOOOOOO']]

tut_levels = [['XXXXXX',
               'XSXXFX',
               'XXXXXX'],
              [('Press arrow keys or wasd to move', 20, (-120, -95)),
               ('Use space to scan your surroundings', 20, (-120, -55)),
               ('Locate the finish tile to complete the level', 20, (-160, 250))],
              [True, True, False],
              ['R   ',
               '    ',
               'A  S',
               '    ',
               'G   '],
              [('These tiles cost 3 battery points', 20, (90, 20)),
               ('These tiles cost 2 battery points', 20, (90, 150)),
               ('These tiles cost 1 battery point', 20, (90, 280))],
              [False, False, True],
              ['OOOOOOOOOO',
               'OGRGAGAGGO',
               'OGSARARFGO',
               'OGAGGGAGGO',
               'OOOOOOOOOO'],
              [('Can you get to the end?', 20, (0, -30))],
              [True, True, False],
              ['H   ',
               '    ',
               'T  S',
               '    ',
               'D   '],
              [('These tiles will recharge your battery', 15, (90, 20)),
               ('These tiles will drain your battery instantly', 15, (90, 150)),
               ('These tiles disappear after you walk on them', 15, (90, 280))],
              [False, False, True]]
